### ISSUE TITLE
auto posting mail to public-audio does not work any more

### ISSUE THREAD

**Issue by toyoshim** [WebAudio/web-midi-api#100]
IIRC, web-midi-api@noreply.github.com sends a mail to public-audio automatically when something is modified at issue tracker. But, it seems to not work for now. Is this changed, or a bug?

**Comment by cwilso** [comment]
Olivier had to switch it off. Because of the way github is set up, anyone replying to a message sent by Github to the Mailing-List would be recognised by github as “coming from public-audio”, added (anonymously, essentially) to the comment stream, and sent by github as a notification to the list.

Great fun for spammers polluting the list with their invitations to join Twitter and so on.

Olivier talked to Github at that point, but their answer was, in essence: tough luck. Most of the group has either joined the github org for WebAudio, or at least starred/followed the repos. But it means we don’t have a mirror of the discussion of github issues on our list archive…
