### ISSUE TITLE
prevent event from being fired when sending a midi message

### ISSUE THREAD

**Issue by jenyckee** [WebAudio/web-midi-api#167]
http://stackoverflow.com/questions/38655130/prevent-event-from-being-fired-when-sending-a-midi-message

**Comment by toyoshim** [comment]
Probably, it's better to explain the context why you file this bug here because spec bugs should be filed here, but implementation bugs should be filed at crbug.com (I assume you are playing with Chrome native implementation).

Anyway, this is expected behavior. You are sending messages through an output port that is expected to route the message to the input port you listen.

**Comment by jenyckee** [comment]
Yes indeed chrome 51 native. This is rather a question than a bug. And I was indeed not sure if messages sent to a IAC output port will be routed back to the input port. Thank you for clarifying that.

Can I expect this behaviour for all midi communication devices? Or is this because I am using a virtual midi device?

**Comment by toyoshim** [comment]
What IAC means is "Inter-application communication".
The driver is designed to communicate between applications, as one can send MIDI messages via output port, and the other can receive them via input port. This is an IAC specific feature and behavior. You can not expect this for other virtual or physical devices.

On Linux, ALSA provides similar pass through devices. Also, you may be able to find a similar driver for Windows. Or you can even connect traditional MIDI output/input ports each other physically through a DIN cable.

**Comment by jenyckee** [comment]
Very useful information! Thanks a lot

**Comment by toyoshim** [comment]
You are welcome. Enjoy!
