### ISSUE TITLE
Listeners for future events

### ISSUE THREAD

**Issue by infojunkie** [WebAudio/web-midi-api#176]
The `MIDIOutput.send` method takes a future timestamp to schedule the sending of the MIDI message. It would be great to allow this method (or the whole output object) to accept listeners (basically callbacks) that are called when the scheduled MIDI message is actually sent. 

A use case would be to advance a visual marker on a sequencing app as the score is being played. The alternative is to have the app do its own scheduling of visual events, but keeping schedules in sync can get tricky.

**Comment by cwilso** [comment]
This would be challenging.  The underlying APIs (e.g. Windows MIDI and Apple's Core MIDI) don't support this kind of notification; it's an opaque send api with future timestamps.

For advancing visual markers, you'd really be much better off managing the timing yourself, particularly as you would want to sync to visual refresh (i.e. requestAnimationFrame) rather than using callbacks.
