### ISSUE TITLE
Access to WebAudio Clock from WebMIDI

### ISSUE THREAD

**Issue by softpunch** [WebAudio/web-midi-api#180]
Hi!

I've been playing with the WebMIDI API for a while now, 
mostly using it to output messages to software and hardware.

I also often use the WebAudio API (and related frameworks like Tone.js).

Ideally, 
I'd like to be able to augment WebAudio apps with MIDI output.

However, 
when outputting WebMIDI messages, 
the timing evaluates against the DOMHighResTimeStamp.

That's not the same clock as the AudioContext.

Yes, it's possible to calculate an offset, 
but when scheduling out notes, 
it becomes difficult to account for two different clocks.

Maybe there is a simple way to do this, 
but I haven't seen it, and I haven't been able to figure it out.

--

For example, 
in this particular sketch (which uses Tone.js), 
I have a loop that schedules notes for both WebAudio and WebMIDI output. 

The loop uses Tone's clock, which is basically the WebAudio context clock.
The WebMIDI output evaluates against the DOMHighResTimeStamp. 

Sometimes the two do not line up, 
and when that happens, 
unintended clipping of MIDI notes occurs.
https://jsfiddle.net/softpunch/6wcu3yon/ 

If I rewrite the sketch using setInterval for the loop (instead of the WebAudio clock), 
that fixes the MIDI clipping issue, but it introduces other issues.
https://jsfiddle.net/softpunch/jezfwtzh/

I realize those aren't perfect test cases (and my code is not as clean & effective as I'd like), 
but hopefully they still illustrate the trouble with having two competing clocks.

Is there any way a parameter could be added to the WebMIDI API that would allow its output to evaluate against a WebAudio Context clock?

That seems like it would be the simplest solution.

Thanks!

**Comment by cwilso** [comment]
This isn't really wise.  There isn't a single WebAudioContext in the system, nor a single "WebAudio clock" - the clock from an AudioContext is representing that particular output device's hardware clock.  If you have two sound output devices, and AudioContexts for both of them, they won't be the same - in fact, they won't even proceed at the same rate (because the audio output devices [likely] have different crystals, over time you'll see one of them is likely slightly faster than the other).

The MIDI world isn't chained to an audio output device, of course, so it uses the system clock.  A system like Tone.js should be able to hide these clocks from you if it wishes.  Your approach of calling send(now) is missing the point; for both audio and MIDI, if you're not telling the system ahead of time to send something, you're probably not doing loops correctly, because you're relying on a JS timeout happening at a precise time.  I'm not totally clear on precisely when Tone.loop schedule callbacks are called; they *should* be called some amount of time ahead of the "time", in order to prime the web audio scheduler, but I suspect they're not.

In short: Tone.js' scheduler isn't any more accurate in schedule callbacks than JS.setTimeout/Interval (it can't be) - it does have the "time" parameter, but you'd need to carefully use that parameter when you trigger Tone synths, too, and make sure your loop scheduler is getting called ahead of time (cf my Tale of Two Clocks article, https://www.html5rocks.com/en/tutorials/audio/scheduling/).   You don't seem to ever use the time parameter in either example, and I *think* you're relying on setTimeout in one example, and Tone.loop in the other (but Tone.loop is setTimeout-based).  In either case, you're relying on *immediately triggering a note* from inside a JS callback, rather than scheduling it ahead of time.  (Okay, for some reason you're delaying Tone's trigger by 0.02 seconds in one case. ?)

Adding @tambien to this thread in case I've misunderstood Tone's scheduler.

**Comment by softpunch** [comment]
Those aren't the best test cases, for the reasons you've pointed out (among others!).

And I understand why it's best not to tie MIDI to audio hardware, at least by default.

I guess I just don't understand why accurate scheduling has to be so complex.

**Comment by softpunch** [comment]
To be clear:
Yes, I've read your (excellent!) Tale of Two Clocks. 
I just don't understand why a new scheduling mechanism has to be created by every dev.

**Comment by tambien** [comment]
i agree with @cwilso. Tone.Loop passes in the time of the event (which is slightly ahead of the current audio context time) in the callback function. doesn't look like you're currently using that value to schedule you're events. then i think it's just a matter of computing the offset between the AudioContext time and the DOMHighResTimeStamp so you can use that same time value to schedule the Tone.js stuff and the WebMidi events.

**Comment by cwilso** [comment]
@softpunch accurate scheduling is... hard.  :)  Especially with Javascript, where the main thread is very congested with chunky things happening.  The goal for both APIs is to provide the bedrock that you can build great scheduling on, but it isn't necessary easy to do; the ideal system for most developers would probably look a bit like Tone.js', but would probably use system time as the core timing, and it would handle pre-scheduling on AudioContext (remember, if you are dealing with more than one audio context, they have different clocks) AND would also put MIDI scheduling into the same system; but in simplifying usability, a library is also limiting what a developer is expected to be able to do, the same way that Tone.js presupposes that it's only using the default audio interface.  (This isn't meant as a negative statement about Tone; it's a choice, and for most developers, the right one.)

I expect, once implementations of Web MIDI are a little more widespread, Tone might want to add in MIDI events; I'd personally suggest that Tone switch to using system time instead of audiocontext time as a default timeframe, which I think could be done relatively seamlessly, but the start/stop of the transport would be problematic.

**Comment by hems** [comment]
Does anyone have any updated information on this? 

Would be nice to get a nice and precise midi-clock running on a browser and on node.js!

As far as I can imagine, the problem with implementing the clock on the browser is that eventually, the UI might choke the clock, for instance, if some slow drawing happens or the browser puts the "interval loop" into the background ( IIRC when scrolling a page some browsers will stop timeouts and requestAnimationFrame, I hope it's not the case/there is a workaround ).

I think some interesting things to look at would be:
 - [Clock using requestAnimationFrame](https://codepen.io/denilsonsa/pen/gPggbj)
 - [rounding settings on DOMHighResTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp)
 - [nanotimer](https://www.npmjs.com/package/nanotimer)
 - [midi-clock](https://github.com/livejs/midi-clock/blob/master/index.js)
 - [WebMidiClockSequencer](https://github.com/starmandeluxe/WebMidiClockSequencer/blob/master/js/sequencer.js)

To make a reliable clock it might be a good idea to implement a "desktop agent" where the user would launch the agent which would also be a WebSocket server, so the browser could detect the "clock agent" on the desktop and delegate the clock messages to that agent in case it exists.

Then somehow we would need the agent MIDI to have a high priority on the system to hopefully avoid any kind of choking and then the browser UI could refresh at "UI Rate" and eventually even "choke" the browser rendering without damaging the timing of the desktop agent.

Does that make sense?

**Comment by rain-sk** [comment]
The best way I've found to maintain accurate timing is to use an external MIDI clock and time application events based on that.

On a Mac, I switched on the internal MIDI server. I set up Live's MIDI-out to route it's clock through the MIDI server. Then with the `webmidi` JavaScript package, I handle `midimessage` events to update the app's internal clock / beat.

At 120bpm, after 35000 ticks (24 ticks per beat), there was a set of 36 different computed deltas (currentTime@tick - time@lastTick), with no more than sub-ms variances.

**Comment by rain-sk** [comment]
Another method I've tried is to pass a ConstantSource through a ScriptProcessor, and bind my timings to its `onaudioprocess` event. This tends to be far less accurate, with some cases of wide variance (I don't have numbers but can re-run the experiment). It seemed to slow down if I unfocused the specific tab / application.

External MIDI is far more reliable.

**Comment by rain-sk** [comment]
It would be great if something like this could be housed as a browser extension. Or if someone released a chromium build with MIDI built in!
