### ISSUE TITLE
classify MIDI messages as user gesture

### ISSUE THREAD

**Issue by chrisguttandin** [WebAudio/web-midi-api#186]
As browser vendors recently began to introduce policies which require a user gesture to unlock certain functionality, it might be worth considering a MIDI message as being a user gesture.

An example of that is Chrome's new behavior which prevents an AudioContext from playing any sound by default. A user gesture is required to start the audio playback. For an app which primarily relies on MIDI messages as user input to trigger audio playback this is impossible because a MIDI message doesn't count as user gesture.

Please see: https://bugs.chromium.org/p/chromium/issues/detail?id=817386. As mentioned in the discussion it makes sense to treat different MIDI messages differently. As an example a 'note on' message could be considered a user gesture whereas a MIDI clock message is most likely not a user gesture.

**Comment by rachelhall** [comment]
Any work arounds on this? I'm trying to solve the same problem.

**Comment by cwilso** [comment]
Although it seemed at first take that this might be a good idea, the WG has concluded that treating MIDI interaction as user gestures would be a bad idea, as we can't promise that some MIDI devices wouldn't "provide a user gesture" without actual user interaction (some MIDI devices may be sending spurious messages without user interaction, and we don't want to enable circumventing of user interaction).

**Comment by AndreVanKammen** [comment]
> Although it seemed at first take that this might be a good idea, the WG has concluded that treating MIDI interaction as user gestures would be a bad idea, as we can't promise that some MIDI devices wouldn't "provide a user gesture" without actual user interaction (some MIDI devices may be sending spurious messages without user interaction, and we don't want to enable circumventing of user interaction).

Couldn't the same be said for some mouses or keyboards? A midi NOTE_ON(9) message should be able to create an audiocontext to play the sound. Now I have to put a big START button on my synth site which needs to be pressed after every refresh which is not very user friendly, all because some midi-keyboard might misbehave :(

The sound start can already be circumvented as ShaderToy starts my piano sound directly after load:
https://www.shadertoy.com/view/XdBSR1

I'm building a synthesizer that works with shaders on the videocard on
https://shadersynth.com
