### ISSUE TITLE
Web Audio API example

### ISSUE THREAD

**Issue by marcoscaceres** [WebAudio/web-midi-api#59]
It would be nice to have a section about how to use this API with Web Audio.

**Comment by cwilso** [comment]
I presume by this you mean "it would be nice to have an example that shows Web Audio and Web MIDI together, e.g. a simple synthesizer".

**Comment by marcoscaceres** [comment]
yeah .. so it goes :musical_note: :musical_note:  :)

**Comment by notator** [comment]
I need (am planning to write, but won't have time for a few months) an on-line MIDI device to which I can send MIDI messages. The device would be implemented in terms of loadable soundfonts.
Maybe that would be easier to write, and more useful, than writing a whole synthesizer?
Whatever example you choose, the proposed section would certainly help me getting started. :-)

**Comment by cwilso** [comment]
Writing a basic synthesizer isn't very hard at all - particularly if you
don't do much in the way of modulation.  For example, the core "Web Audio
synth engine" for my sine-wave-with-ADSR-envelope synth in the synth
template I wrote is like 18 lines of code (the Voice constructor and
.noteOff functions).  All the rest is just user interface, essentially.
 Writing a monophonic synth would be even easier, particularly if you don't
care about providing UI.

A downloadable soundfont synth engine is actually quite a complex
sample-playback synthesizer.

**Comment by marcoscaceres** [comment]
Something around the 20-50 lines of code that we can throw into the intro or appendix would be ideal. @chrislo, if you want to share some code, I can help clean it up or whatever. Just needs to be really simple.

**Comment by chrislo** [comment]
@marcoscaceres I could do that, I have some kicking around - but did you mean @cwilso?

**Comment by marcoscaceres** [comment]
Sorry @chrislo, yes. But either would be great :) It would not hurt to have multiple examples if it makes sense and show different ways of using the API.

**Comment by cwilso** [comment]
OK, I built a web audio/web midi monosynth example with no UI: http://cwilso.github.io/monosynth/.  The actual script is ~85 lines.  How would this do?

**Comment by notator** [comment]
I can see the point of keeping it simple, of course. But maybe its too simple? I could do that just by reading the introductory Web MIDI and Web Audio tutorials.

Could there be room somewhere for one or two more advanced tutorials dealing with soundfonts? They are not covered properly anywhere else, as far as I know, and they are very typical MIDI resources.
I'd like to be shown how to respond to a single incoming noteOn message by playing a note on patch 6 (GM Harpsichord) followed by a note on patch 73 (GM Flute).

Soundfonts are important because their use would allow Web MIDI applications to use _any_ sounds predictably, not just those that happen to be available on the local computer or a possibly rather limited on-line synthesizer...

Just brainstorming... :-)

**Comment by cwilso** [comment]
Keep in mind we're talking about an example that is embedded in the spec itself.  I don't want to have a super-long sample there.

Soundfonts are a good technology.  Implementing a Soundfont player would be a valuable thing, but I don't think it's sample code for the spec.

**Comment by notator** [comment]
Understood. :-)

**Comment by cwilso** [comment]
Fixed by https://github.com/WebAudio/web-midi-api/commit/997c2adfdda083b59339e66a43babaa09f53fb93.
