### ISSUE TITLE
MIDIPort#open() necessary?

### ISSUE THREAD

**Issue by jussi-kalliokoski** [WebAudio/web-midi-api#75]
This issue is a spinoff from #2, where there has been a lot of discussion about getting rid of the MIDIPort interface and if I'm not mistaken we're approaching a consensus that if there needs to be an explicit way to enable the port for use, it shouldn't be the `getInputs()`/`getInput()` separation.

What I want to discuss in this issue is whether or not we actually want an explicit way of doing it at all. To recap, the issue is that some platforms (Windows) only allow exclusive access to ports, and we don't want the UA to get exclusive access to all available MIDI ports when MIDI access is requested because that would prevent interaction with other software using MIDI amongst other things.

However, we could also define heuristics like that when `send()` is called or an event listener is assigned, try to open the port. This would reduce the application complexity for accessing a port significantly, but the side effect is that there are a lot of cases where for example another application has reserved the port so stuff just doesn't work and the application has no way of knowing and thus informing the user that something is wrong. The other side of the coin is that the `open()` method wouldn't do anything at all on for example OS X and Linux and I fear that authors would often just ignore the errors that it could throw anyway making it somewhat useless.

This is quite an obvious tradeoff, the question is which tradeoff we want to make. Thoughts?

**Comment by jussi-kalliokoski** [comment]
Another thing to consider is that we can't be sure that even Windows will have the problem in the future (in fact I don't know whether this effects Win8)

**Comment by cwilso** [comment]
My personal preference is not to design specifically for Windows' shortcoming here, and define heuristics like you suggested.  If the worst thing that happens is Web MIDI apps on Windows are a little aggressive about claiming ports, I think that's fine.

**Comment by jussi-kalliokoski** [comment]
> My personal preference is not to design specifically for Windows' shortcoming here, and define heuristics like you suggested

Whoops, I actually thought I'd replied to this, but it seems I hadn't. Anyway, I agree.

**Comment by marcoscaceres** [comment]
FWIW, I agree also.

**Comment by cwilso** [comment]
Marking as v2 for consideration if necessary.

**Comment by cwilso** [comment]
See bome's comments in #104.

**Comment by bome** [comment]
I see how `send()` and setting the `onmidimessage` handler can be used to implicitly open the port, and destruction of the object will close it. However, I assume that timing of the latter will be indeterminate.

> The other side of the coin is that the open() method wouldn't do anything at all on for example OS X and Linux

CoreMIDI and ALSA do have equivalents to an open() function, which allocate the resources, and put the port in a "ready" state. For MIDIOutput, it gives the programmer the assurance that the first call to `send()` will a) not fail and b) execute without delay. For MIDIInput, it gives you assurance that the port will actually receive data (when coming in). A `state` attribute will nicely complement this (see #105).

> (...) and I fear that authors would often just ignore the errors that it could throw anyway making it somewhat useless.

I'd rather like to create an API that does give programmers the tools to write "good" software that behaves well with everything else.

Maybe it's practical to make `open()` and `close()` optional, for those that do like explicit control. It also gives a hint to lazy programmers that it might be worthwhile to think about resource allocation and deallocation...

**Comment by agoode** [comment]
Yes, for Alsa, it would be nice to be explicit here. Right now the Chrome implementation opens every MIDI device it finds so that they are all ready at all times. This has the potential to fail if it hits limits on file descriptors or other resources.

Making `open()` and `close()` optional is fine, if we don't want to break compatibility.

**Comment by cwilso** [comment]
Chrome's implementation today is overly aggressive, and not what we want to ship.  It doesn't need to open devices so aggressively, and it shouldn't.

**Comment by agoode** [comment]
Agreed. What I was suggesting was that I think we need `open` in the API, to allow implementations to be less aggressive while still ensuring low latency on the first `send`. I think the options are:
1. No explicit `open`. Implementation doesn't preopen any devices. The first `send` can result in high latency while system-dependent open occurs.
2. No explicit `open`. Implementation preopens all devices to eliminate initial `send` latency. (Considered too aggressive.)
3. Explicit (perhaps optional) `open`. Devices opened when requested, no extra latency on initial `send`. If `open` omitted by client, fallback to option 1 above.

Sound right? Or am I missing another way?

**Comment by toyoshim** [comment]
I agree that opening all devices while having MIDIAccess is too expensive on some platforms.
Opening devices on demand will be reasonable, but I'm not sure having open() method is useful just to reduce the first latency on some platforms. If we wan to have a open(), it should be an asynchronous function, and may fail because of device disconnection, or another application using it. So it makes API complex unnecessarily. Everything go asynchronously, so open() ensures  nothing. It may be disconnected, or obtained by another application just now even it returns successfully.
What happens if we provide "state" attribute as #105? It means that even an application owns a MIDIPort, it may be unavailable somehow. In such a situation, opening a device on send() on demand makes sense.
Applications may want to call send() with a system reset message or something like that for pre-opening a device to reduce the first latency. Actually, in many cases, applications send messages for initializations and they are not latency sensitive.

**Comment by toyoshim** [comment]
If send() fails, data can be stored into an internal message queue until the device gets back to online again. flush() #102 may be useful here?

**Comment by bome** [comment]
Thanks for your comments!

> If send() fails, data can be stored into an internal message queue until the device gets back to online again. flush() #102 may be useful here?

very dangerous. Usually, MIDI does not retain queued messages upon a disconnection. I cannot see a use case, either.

> Applications may want to call send() with a system reset message or something like that for pre-opening a device

yes, that will work. Or even `send(null)` or a zero-sized message. But it really is an overload of the `send()` method. We will need precise documentation and specification how this implicit open works, so that it is implemented and used correctly.

However, from my experience, semantic overloads usually make an API more complex and error prone for implementers and for users (programmers), because the method names are not self describing.

And all this does not help us for an explicit `close()`.

>  If we want to have a open(), it should be an asynchronous function

sounds good to me -- I guess it's a common pattern in ECMAScript and doesn't seem complex to me.

In general, I'm still persuaded that we should give programmers the tools to get fine grained control over the devices. Only that will allow them to write MIDI software that has a consistent and deterministic user experience (e.g. MIDI port display, error messages, ...). It's OK to have implicit behavior and/or high level methods for quick and dirty MIDI apps. But we should also target more serious applications.

**Comment by agoode** [comment]
I do think we want `open` and `close`. On Linux (with ALSA seq), this actually changes the state of devices. Other clients on the host can open MIDI devices exclusively, and without a `close` API we can't easily release the hardware. Likewise, `open` for writing will fail if the device happens to be exclusively connected by something else. Only by opening explicitly can we avoid this situation.

Note that `open` and `close` only make sense for writing. For reading, event handler registration and deregistration should be the equivalent operations.

**Comment by cwilso** [comment]
@agoode do you have any idea of the time cost in open/close?  I'm presuming this would have to be a Promise API.

**Comment by toyoshim** [comment]
I think it should be async APIs if we really need them.
Another choice is using MIDIConnectionEvent even to notify open and close completion. It will be handled by onstatechange handler or something like that.
Anyway, the port state can be an intermediate state, like opening or closing.

**Comment by agoode** [comment]
@cwilso Typically it is instantaneous, but the initial open might take a few seconds if drivers need to load.

**Comment by cwilso** [comment]
Then it needs to be Promise-based (and have a connectionstate event).  Bleah.

I'd rather not have to open() on an input port (use event handlers for open inference).  Below is an IDL for open() only on outputs.  If we do have open() on input ports, I'd just have the promise return the objects with the eventhandler (and the send()).

So, with open() only on output, this would be something like (MIDIInput left out, since it doesn't change):

```
interface MIDIAccess : EventTarget {
    readonly    attribute MIDIInputMap  inputs;
    readonly    attribute MIDIOutputMap outputs;
                attribute EventHandler  onconnectionstatechange;
    readonly    attribute boolean       sysexEnabled;
};

interface MIDIConnectionEvent : Event {
    readonly    attribute MIDIPort port;
};

enum MIDIPortState {
    "connected",
    "active",
    "disconnected"
};

interface MIDIPort : EventTarget {
    readonly    attribute DOMString    id;
    readonly    attribute DOMString?   manufacturer;
    readonly    attribute DOMString?   name;
    readonly    attribute MIDIPortType type;
    readonly    attribute DOMString?   version;
    readonly    attribute MIDIPortState state;
                attribute EventHandler onconnectionstatechange;
};

interface MIDIOutput : MIDIPort {
    Promise open();
    void close();
    void send (sequence<octet> data, optional double timestamp);
};
```

**Comment by bome** [comment]
This looks good to me. Except that I don't understand the architectural difference of open() for MIDI OUT and for MIDI IN. Yes, we already have an implicit way for opening and closing MIDI IN by setting/unsetting the event handler. But I don't think that's particularly good API design. And opening a MIDI IN port may also take a few seconds for the driver to initialize etc. So it would be very useful to have an asynchronous open() for MIDI IN with a Promise on return.

Thinking of it, explicit open() and close() will interfere with the implicit open and close: it would be rather surprising. IMHO, it's a hack anyway.

Naming:
- State "active": I'd prefer "opened" or "open", because that's the name of the function to transition it to that state. Moreover, the meaning of "active" varies a lot in different media API's.
- Event Handler `onconnectionstatechange`: why not `onstatechange` or `onportstatechange`? would be more consistent with `MIDIPortState`.

**Comment by jussi-kalliokoski** [comment]
I agree with Florian on the state naming as well as removing implicit open for MIDI IN.

As for `connectionstatechange`, a little bit of inconsistency between `state` and `onconnectionstatechange`, and also this reminds me of XHR's `onstatechange`; very ambiguous, I'd prefer to have nodejs-style separate events (`onconnect`, `ondisconnect`) so that you can listen to the events you care about instead of having a `switch` in the event handler.

**Comment by cwilso** [comment]
Does either of you have a reason for why implicit open is bad, other than
the ambiguous "[not] particularly good API design"?  Because I'm not
excited about forcing developers to take more steps that do not seem to
improve anything, or have any positive attributes.  For inputs, as a
developer I want to set up an event handler, and it is unambiguous when I
am expecting the port to start listening for events - I set up an event
handler.  I think open on inputs is totally unnecessary, as it is
unambiguous. I think poor underlying MIDI APIs are the only reason we need
to have open() on outputs, so I'm not wild about that either, and I have a
strong preference to imply opens on outputs too, because I think we should
be making it easier for developers, not more complex.

Note that the Promise for output open() is a convenience, presuming that
you'll frequently want to send initialization as soon as the port is open;
input does not have that scenario, and you can always handle connection
events anyway.

I'll ask for further input on separate events vs single, because opinions
don't seem to be shared there.

On Sun, Oct 26, 2014 at 6:09 AM, Jussi Kalliokoski <notifications@github.com

**Comment by jussi-kalliokoski** [comment]
> Does either of you have a reason for why implicit open is bad

Consistency between the two types of ports, and also developer expectations - when you start listening to a port and the opening is implicit, you're going to possibly lose some events until the port is open, so I'd prefer the flow to reflect what actually happens, i.e. you open the port, and only then can events start flowing in so that's when you start listening.

Are there any examples out in the wild where starting to listen to an event triggers a state change as a side effect?

**Comment by toyoshim** [comment]
+1 on Florian's new naming.

For implicit open, another solution to make the API consistent is to modify send method as "open the port if it is closed, and send the data". Thus, introducing open() and close() does not break existing code compatibility, and make these implementation optional, as "open() and close() may do nothing in some platform." In such platforms, the state may be `open` from the beginning, and may not be able to close the port.

In Chromium, at least Windows, Linux, and Chrome OS ports will implement it.

**Comment by cwilso** [comment]
@toyoshim yes, that is exactly what I meant when I said " I have a strong preference to imply opens on outputs too" - we should imply open() on send if it's not already open.

@jussi-kalliokoski How are you going to "lose some events until the port is open?"  If you're doing a scenario where this matters (e.g opening an input port from a sampler that you already have an output port open to, and you're doing a sample dump, and you need to make sure you don't miss the first "ACK" message back based on your send), you would use open() (because you can wait until you know it's open - and you KNOW it has successfully gotten access to the port).  There are certainly plenty of event-listeners that trigger performance differences; side effects beyond that, I don't know.  As the side effect here is "makes MIDI port unavailable for other apps in host systems that only support exclusive mode", that seems like a minimal effect.

Again, I have a strong preference not to introduce extra steps for developers when most of them do not need to even understand the difference.

**Comment by ghost** [comment]
This might be a stupid suggestion but why not make Web MIDI exclusive to Web Workers? That would solve performance related issues as well as removing the need for any asynchronous APIs. The latter really isn't pleasant to work with when dealing with anything MIDI/audio related.

**Comment by cwilso** [comment]
It's not true at all that moving to workers would remove the need for async APIs; additionally, audio APIs tend by nature to be asynchronously defined.

Additionally, Workers aren't all that well-embedded in developers' minds yet; I would not want to require developers to understand and implement them (including the postMessage back-and-forth to communicate with the main thread) in order to use MIDI at all - and many use cases are not so time-critical that you'd need to avoid potential main-thread congestion.  (By contrast, Audio Workers tend to be better encapsulated and narrower use case.)  I agree MIDI should be available to workers, but I don't see a reason to limit it to workers.

**Comment by ghost** [comment]
In retrospect it was a bit of an extreme suggestion. I just feel the more of these performance hungry APIs can be moved (in part or whole) to different threads the better.

I was recently playing around with decoding MIDI files in a worker (it would have killed the main thread) and everything was going well until I needed to get the data over to the main thread in a format that was Web MIDI friendly. It's possible to do but it requires a good amount of work to push everything into array buffers for transferring. Serialization would be far too heavy.

Anyway, just throwing that one out there for better or worse :)

**Comment by toyoshim** [comment]
Hi, I send a proposal that will reflect discussion at this thread.
WDYT?
IIRC, there were no discussion about what happens if an implicit open device operation behind send() or setting handlers fails. So, I defined it to deliver a MIDIConnectionEvent without updating the state attribute.

**Comment by cwilso** [comment]
Fixed with https://github.com/WebAudio/web-midi-api/commit/1fec2aae57c9048278dc606a8860cc0661a6593f.
