### ISSUE TITLE
Promise usage problems

### ISSUE THREAD

**Issue by domenic** [WebAudio/web-midi-api#90]
Promises can only be resolved with one value, whereas you have created a custom MIDISuccessCallback type which takes two values. That is not how promises work; you just say "the returned promise is resolved with x".

Similarly, asynchronous functions should be rejected with something that is an `instanceof Error`, which `DOMError` is not; you should use `DOMException`. And again, there is no need to create a custom MIDIErrorCallback; just say that the returned promise is rejected with a `DOMException`.

More promise API guidance here: https://github.com/domenic/promises-unwrapping/blob/master/writing-specifications-with-promises.md

**Comment by toyoshim** [comment]
Hi Chris,
Web MIDI on Chrome is going to use the proper Promise implementation, and is going to remove the second argument on MIDISuccessCallback because of the reason Domenic described here. I think the second parameter is not useful, and if needed, we can add it as an attribute of MIDIAccess. WDYT?

**Comment by cwilso** [comment]
SGTM.  Hmm, thought I'd done that originally, actually - must have not
finished that bit.

**Comment by domenic** [comment]
Actually, `DOMException` is not `instanceof Error` either; it turns out neither `DOMException` nor `DOMError` is currently suitable for usage with promises. See https://github.com/domenic/promises-unwrapping/issues/84

**Comment by cwilso** [comment]
So, this should just be an Error?

**Comment by domenic** [comment]
Oh man sorry about that.

I discovered that DOMException is in fact an `instanceof Error`, but this is hidden in a different spec from the one DOMException is defined in.

So, the final answer is: use DOMException!!

**Comment by cwilso** [comment]
So this should be something like:

 Let error be a new DOMException. This exception's .name should be "SecurityError" if the user or their security settings denied the application from creating a MIDIAccess instance with the requested options, "AbortError" if the page is going to be closed for a user navigation, "InvalidStateError" if the underlying systems raise any errors, or otherwise it should be of type "NotSupportedError".

Yes?

**Comment by domenic** [comment]
Sounds good to me! Maybe s/type/name in the last sentence.

**Comment by cwilso** [comment]
Whoops, yes.  Thanks.

**Comment by yutakahirano** [comment]
[MIDIPort.open](http://webaudio.github.io/web-midi-api/#widl-MIDIPort-open-Promise-MIDIPort) and [MIDIPort.close](http://webaudio.github.io/web-midi-api/#widl-MIDIPort-close-Promise-MIDIPort) need to be fixed as well.

**Comment by cwilso** [comment]
Quite right.  Thanks for the catch, @yutakahirano !
